### PR TITLE
update mqtt.py

### PR DESCRIPTION
**Pull request by pankeshpatel**
Changed the file in example. Revise the Device APIs. add necessary import to support APIs. Update the MQTT server from local to  publicly available server "mosquittos"

### CODE REVIEW

**Comment by bgusach** [comment]
That was a nice little addition. Thanks.

**Comment by kartben** [comment]
@bgusach Please do not merge pull request if the IP validation fails :-) It would seem @pankeshlinux did not sign off his commits and/or does not have a CLA in place. Can you please have a look?

**Comment by bgusach** [comment]
Hi @kartben, I guessed that the merging entails that I, as a official commiter, approve the suggested changes. 

Seems not to be the case, so I'll revert the commits and manually apply a patch.

**Comment by kartben** [comment]
@bgusach It is not about approving the changes, it is about making sure the contributor has signed the Eclipse Contributor Agreement.

"The purpose of the Eclipse Contributor Agreement (ECA) is to provide a written record that a contributor has agreed to provide their contributions of code and documentation under the licenses used by the Eclipse Project(s) to which they are contributing. All contributors who are not already committers on the Eclipse Project to which they are contributing must digitally sign the ECA."

See also https://www.eclipse.org/projects/handbook/#resources-github

**Comment by bgusach** [comment]
OK, I understand. 

Commits were reverted yesterday and a patch with the changes applied. Is this OK? Can I handle such cases in the future this way? or rather systematically reject any non-ECA contribution...

**Comment by fpatz** [comment]
Every contributor needs to have an ECA, I think. We should mention this in the README and make the process transparent.

**Comment by kartben** [comment]
even better, you may want to add a CONTRIBUTING.md to the root of the repo.
There's many examples in other Eclipse projects, e.g
https://github.com/eclipse/kura/blob/develop/CONTRIBUTING.md

Thanks!

**Comment by bgusach** [comment]
Ok, I'll add a CONTRIBUTING.md, revert any change, and reject any pull request from a non-ECA contributor.

I understand that is the official and right thing to do, but I think we are overreacting a little here. This "contribution" was not even in the source code, it just consisted of changing a URL in an example.

**Pull request merged**
